language: java
sudo: false
jdk:
- openjdk11
env:
  global:
  - secure: "LT4nMSKCu4qL+jQ80BdBIOqFO3GCyAPoxNkskS0q0wvscDpEx2bvFZa9KF6/dQxubhWnfACqWxxPKfF3VadfZoKn1z01TaZ/rKHkA5GedZweFO0wBIvi/gDIcAxVX0oPOkIruugYY3iDOzOqTUuBM686cW1XWs0LEV7qPTb6KM02/IeckQs+P9SSiarqSKROlQ8dABGdyxJTXheHHphFu4mDiQsi1vtub6OoQclKLLuK2MJvFiyDeZDYYXAnjFNC/pcBUBjr5b886zPB6HLLGgvQKRLvzQudedz08ZlJdnt3k6u7HvLINbs00U60fnD/+4krQQN4EEx0Natv4L1SxFjYO4wFK2FTCKoBMkVfjINqiWzmb/yhoG33Sw9VGiYdcV45QbH32CX1oiATohV+79gfIID6p3UOL1SZuELR2XzRq70K4Kw2BXig99a0+LjYCv4ynnzetqyWVZIdhBQ1Srf/4GxUwF21Urn9TJCNr2F5BcbqGrMUMvXNjTI0WqQCTMqM+Ha9Rbe27GG7ZMtMUHd83YWP0GDiSIg2S0T0lNL2e9iQGXsGBiX3Bz+E3HEWhnE4l6XKYVgn3NXrlDjwc2B6GTGeImZXkrbFFJwQihUSujj5H6l/+5a7NxbyA1MvzNwjeTaHzdNdYovTq6ywydVtF/Kt5h7oA2KmUoajaFs=" # CODACY_PROJECT_TOKEN
  - secure: "E5T75tGRnA6kplWe1/gxnvHzzZn5Z1/Wb58Th67Nm0MHmGK8PnR0tukcQbfNPsGMp3P3lb+wmTFfNeiuWXfan88F5CrktBJYJgsNQxWMnNk1fcT+QNyHlm7Xngpm/ntHGJCDGF/yFuJLvwzlD6SDSTAU709MxB60aoKVDtylGkkLhVWpNMtSNwgjRu2pzGjR8VxOWckt4zQw4mSXQfVZqHsQAPWGTGKktN08/ff71FyoO2uKffnzhLny9wjsUx7ora2/EyKDqFpkqMvOEN2njcMc6QF5M041VzoYw/gsURowImRHP385xqqg4kl45Fb7unHVv2rz1rRwSbWlJawGBRrzkLR+B1+sE2Jij0o30Wifijwh3HRtHIR7k0T7f893xN7B6du4VhKhKrYMVUn9xVILEWElkwHb50BnBP/3zTfrm38/nlW+KtY+vBSrvqbfAfaoKsJZQuNcJ8ezcvdMXVHuOWixozJpHROFvLRzMJJCB07mSNdGTgX8jI34se+299/M0sLpT5N8PQ8WJjs5h+YkK6FLL7KqEOR6QWHkgYamZirQF2dqYw1Rdw37x5Lad6Py938lBn5P5c+Gx00D43MwoN31tiTWdp/NlUyFbEPst225Fj1/VpLDnZiek+QcgAf6PzpejeKyS018EEiO10CYgb2J38nivQ6RuvU9kII=" # BINTRAY_API_KEY
install:
- curl -o $HOME/.m2/settings.xml https://gist.githubusercontent.com/cryptobot/cf5fbd909c4782aaeeeb7c7f4a1a43da/raw/e60ee486e34ee0c79f89f947abe2c83b4290c6bb/settings.xml
- mvn source:help javadoc:help dependency:go-offline -Pdependency-check,coverage,release
before_script:
- mvn --update-snapshots dependency-check:check -Pdependency-check
script:
- mvn clean test jacoco:report verify -Pcoverage -Dorg.slf4j.simpleLogger.defaultLogLevel=debug
after_success:
- curl -o ~/codacy-coverage-reporter.jar https://oss.sonatype.org/service/local/repositories/releases/content/com/codacy/codacy-coverage-reporter/4.0.3/codacy-coverage-reporter-4.0.3-assembly.jar
- $JAVA_HOME/bin/java -jar ~/codacy-coverage-reporter.jar report -l Java -r target/site/jacoco/jacoco.xml
cache:
  directories:
  - $HOME/.m2
deploy:
- provider: script
  script: mvn clean versions:set -DnewVersion=${TRAVIS_TAG} deploy -DskipTests -Prelease
  skip_cleanup: true
  on:
    repo: cryptomator/cryptofs
    tags: true
- provider: releases
  api_key:
    secure: MuPqDpIJweuPZnZN2jVPPeiYc56r5Hr1TP+7s+caH+/Z0ToQQbsewRZtwvN1/vsf34XGH+tPTZfzkvakNbKuqgy1H94Mtz7yEyn3zo5RvQGxe2/aI3mX//CR4EuJBBrAxqcrJgyyuElE1WrtJC/2Lc0vGStOV34bZUMpXil2MPd3vNTC1Vufp/qJDYknAXka5S+oRsogKmKvXrdtsAsfn9iRwRflMtDe7y6qD18vQPl6LkIxq+BV68z/CEgHBvaO9TlxabYcOwFCFhwVDye0XIvoewS+UZpgc1zxTOcNeRfjYzKuBwsgpa2/aE500pfHaWqwA/1vHsY0yrEIqYN7V+kA8D+QAHmMzrtbJ68nrH59et++IE/BTBND4bd5BE8IUf5Knsr1OYlP8QIUNG69sYka1Wms8sZqQiTW3hKfg6zCcB85fUY7TwVZGlRBDimj0DDcNlItuTdLMjMWn86NsxCk33r2cgy6isY9xCK+KNu7sBBbd5hOTLvmOgtSMi8+txiKth+/3DuUqj4s6kjldUUAeJv7KZ8UkbBn30E8Vl7cGPELVH6slcpcSv0xxgVNkehzYJjx0OAN5LomxJEfuVy8FFjWx8cffY/NJcNuqem0s36rNZEA5NEdYqIWL9XCLrUGytO4eBxVjfQNXjnAYUy5AKpcRrVaPswsHYQ7/XI=
  file_glob: true
  file:
  - "target/dependency-list.txt"
  - "target/*.jar"
  skip_cleanup: true
  on:
    repo: cryptomator/cryptofs
    tags: true
after_deploy:
  - "echo '{\"close\": \"1\"}' | curl -v -X POST -u cryptobot:${BINTRAY_API_KEY} https://api.bintray.com/maven_central_sync/cryptomator/maven/cryptofs/versions/${TRAVIS_TAG}"
